Project.toml
README.md
src/AnalyzeRegistry.jl
test/runtests.jl

Hi @giordano, I've tried to address #5 here. I decided to clone to a directory named by the UUID instead of the package name, to allow one to reuse the same `root` for multiple registries which could possibly have packages with the same names (but different UUIDs). I also added a `uuid` field to the package so it was easier to find where it would be (i.e. if you do `pkg = analyze_from_registry!(root, ...)` then `joinpath(root, string(pkg.uuid))` gives you the folder it got cloned to).
I also changed the `analyze` function to be the one using the source code directory, and what used to be called analyze is now `analyze_from_registry`, which I thought might be clearer. Something kind of fun is that you can use `analyze` with `pkgdir` so that you don't need to clone for packages you've …

Reorganise

---

src/AnalyzeRegistry.jl
test/baduuid.toml
test/missingquote.toml
test/runtests.jl

In #6, I changed from using the name and UUID from the registry to instead parsing it from the Project.toml. I did this just because we need to parse from the Project for `analyze` (where we don't have registry information) and it was easier to do it the same way in either case. I realized however that this wasn't a good idea, because we don't know that the master branch of every package has a valid Project.toml (the registered releases do, but anything could have happened since then).
So instead, here I only parse the Project.toml when needed, i.e. when you don't supply the name and UUID as keyword arguments to `analyze`. I also made the project parsing much more robust, so it shouldn't throw even if the Project doesn't exist or is invalid.

only parse Project.toml when necessary, and parse more robustly

---

README.md
src/AnalyzeRegistry.jl
test/runtests.jl

This PR changes the registry to be a keyword argument, and allows passing a list or varargs package names as strings to look up from the registry. I found it just makes it a bit less tedious than lots of `joinpath(general_registry(), "F", "Flux")` stuff. (I had a non-breaking version of this in #11 but I pulled it out here since it's entirely separate).
```julia
julia> pkgs = find_packages("AbstractPlotting", "GLMakie", "CairoMakie")
3-element Vector{String}:
"/Users/eh540/.julia/registries/General/A/AbstractPlotting"
"/Users/eh540/.julia/registries/General/G/GLMakie"
"/Users/eh540/.julia/registries/General/C/CairoMakie"
julia> results = analyze_from_registry!(root, pkgs) #...
```
(This is a breaking change!).

tweak find packages API

---

src/AnalyzeRegistry.jl
test/runtests.jl

This makes some minimal changes to close #28. We just check that the subdir exists for before looking for licenses / code in it. I also added the `subdir` to the `show` method; I think this is good either way since it's interesting to see it's a subdir package, but is particularly important when we can't parse the Project.toml so we don't have a name, and the repo alone doesn't identify the package, ref https://github.com/giordano/AnalyzeRegistry.jl/issues/28#issuecomment-782979547.
```julia
julia> analyze_from_registry!(root, find_package("SnoopCompileAnalysis"))
Package Invalid Project.toml:
* repo: https://github.com/timholy/SnoopCompile.jl.git
* in subdirectory: SnoopCompileAnalysis
* uuid: 00000000-0000-0000-0000-000000000000
* is reachable: true
* no license found
* has …
```

Fix for subdirs that doesn't exist at the git repo HEAD

---

docs/src/index.md

Looks like I forgot to update the Package fields in the documentation when switching to a license table.

fix out of date description of fields

---

src/AnalyzeRegistry.jl
test/runtests.jl

I reorganized dispatch a little bit so that everything lowers to `analyze_path` once you've got the code locally somewhere. I wasn't totally sure what the best approach was here, but I thought it was good if there was a way to avoid the parsing when you already know it's local.
Let me know what you think!

allow `analyze` to accept URLs

---

.github/workflows/ci.yml
docs/src/index.md
src/AnalyzeRegistry.jl
src/count_loc.jl
test/runtests.jl

Maaaaybe this test would catch some of our thread-safety bugs? There's only 2 packages though, and I'm not sure FLoops actually uses multiple threads with such a small vector...

Add threaded test and misc docs fixes

---

src/AnalyzeRegistry.jl
test/runtests.jl

Also, make the test with the non-existing repo more robust: GitHub doesn't allow
`!` in repo names, so trying to clone `DOES_NOT_EXIST!!!.jl` would fail
immediately anyway.  Instead we want to test that trying to clone a repo with a
valid name doesn't prompt for username/password.

Close STDIN to prevent git from prompting for username/password

---

Project.toml
docs/src/index.md
src/AnalyzeRegistry.jl

To drop the FLoops dependency. That + GitCommand 3.0 would bring us down to a small set of light dependencies.

Use `Threads.foreach` for load-balanced threading

---

Project.toml
docs/make.jl
docs/src/api.md
docs/src/index.md
docs/src/serialization.md
src/PackageAnalyzer.jl
test/baduuid/Project.toml
test/license_in_project/Project.toml
test/licenses_in_project/JuliaProject.toml
test/missingquote/Project.toml
test/runtests.jl

I'm undecided between AnalyzePackage (singular) and AnalyzePackages (plural).
Thoughts?
Fix #20.

Rename package to PackageAnalyzer

---

.github/workflows/ci.yml
.github/workflows/docs.yml
docs/src/index.md
src/AnalyzeRegistry.jl
src/PackageAnalyzer.jl
test/runtests.jl

For repos with > 500 contributors, the GH api only returns 500 (though it seems like sometimes fewer, e.g. 404 for JuliaLang/julia).
This PR passes `anon=true` so that GH returns us all the contributors, but for some it will return GH info like their GH id and login, and for others it will return just a name and email, which is presumably not deduplicated if one used multiple names/emails but with the same GH identity.
To handle the variety of responses, I switched the object we store to a table that uses missing entries for id/login or name/email depending on what we have.
Draft since it isn't totally clear if we want to go this way (now we probably have duplicate entries instead of missing entries) and I haven't updated tests or docs.
Example:
```julia
julia> …
```

collect anonymous contributors

---

src/PackageAnalyzer.jl
test/runtests.jl

This allows things like
```julia
using PackageAnalyzer, PkgDeps, DataFrames
DataFrame(analyze(find_packages(keys(dependencies("DataFrames")))))
```
to not emit warnings.

Don't emit warnings when not finding stdlibs in `find_packages`

---

docs/Project.toml
docs/src/serialization.md

I think this is a better way to handle serialization. The difference is that we don't get `Package` objects back out post-serialization, instead we get a table.
The advantage is that if we add more fields to `Package`, this kind of serialization won't break, since we aren't trying to fit the result of deserialization back into a `Package` object. We are just getting a table, and it's easy to combine tables with more or less columns (e.g. `DataFrames` has `vcat` and `append!` methods with `cols=:union` option to union all the columns).
The disadvantage is that again you aren't getting a `Package` back, just the contents of the package as a row of a table, so you'd need to do some more work to reconstruct the Package object if that's what you really wanted. However, in our usage that …

update serialization recommendation in docs

---

Project.toml
docs/src/index.md
src/PackageAnalyzer.jl
test/runtests.jl

This allows us to work with compressed registries, and also offloads some of the parsing and path manipulation there.
I bumped it as a breaking release because we had documented `RegistryEntry`'s as a way to use PackageAnalyzer, and this drops support for them in favor of RegistryInstance's PkgEntry object.

update to use RegistryInstances

---

Project.toml
docs/src/index.md
src/PackageAnalyzer.jl
test/runtests.jl

This adds a `tree_hash` field to `Package` which records the analyzed tree hash. My ultimate goal is to analyze a Manifest, and actually analyze the code according to the tree hashes in the manifest. But I think one first step is to just record the version that was actually analyzed.
In general, since we do a shallow clone of the latest version, the tree hash we get won't match the tree hash of a registered version. But if the package has happened to register the latest commit, we do get the correct hash:
```julia
using PackageAnalyzer, RegistryInstances
name = "RegistryCI"
pkg = find_package(name)
info = registry_info(pkg)
v = maximum(keys(info.version_info))
hash = bytes2hex(info.version_info[v].git_tree_sha1.bytes)
result = analyze(pkg)
result.tree_hash == hash
```
I don't want to add …

Record the tree hash of the analyzed (sub)directory

---

Project.toml
src/LineCategories.jl
test/runtests.jl

```julia
julia> @time analyze("WinEncoding");
4.360394 seconds (61.29 k allocations: 26.116 MiB)
```
still slow, but down from a reported 5 mins

perf bugfix: only get line number, not col

---

src/PackageAnalyzer.jl

This PR adds support for [package extensions](https://pkgdocs.julialang.org/v1.9/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)) by counting lines in the `ext` directory.
**Before this PR**
```julia
julia> using PackageAnalyzer
julia> analyze("https://github.com/hyrodium/BasicBSpline.jl")
PackageV1 BasicBSpline:
* repo: https://github.com/hyrodium/BasicBSpline.jl
* uuid: 4c5d9882-2acf-4ea4-9e48-968fd4518195
* version: missing
* is reachable: true
* tree hash: 9b4f65180a415c9a61975b1dafaee2cdd07011d1
* Julia code in `src`: 2444 lines
* Julia code in `test`: 1828 lines (42.8% of `test` + `src`)
* documentation in `docs`: 1237 lines (33.6% of `docs` + `src`)
* documentation in README & docstrings: 348 lines (12.5% of README + `src`)
* has license(s) in file: MIT
* …
```

Add support for package extensions in `show` method

---

src/LineCategories.jl
src/PackageAnalyzer.jl
src/count_loc.jl

Found via https://ericphanson.github.io/ExplicitImports.jl/dev/api/#ExplicitImports.print_explicit_imports
````julia
julia> using PackageAnalyzer, ExplicitImports
julia> print_explicit_imports(PackageAnalyzer)
Module PackageAnalyzer is relying on implicit imports for 10 names. These could be explicitly imported as follows:
```julia
using CodecZlib: GzipDecompressorStream
using LicenseCheck: find_licenses
using LicenseCheck: is_osi_approved
using PackageAnalyzer.CategorizeLines: Blank
using PackageAnalyzer.CategorizeLines: Code
using PackageAnalyzer.CategorizeLines: Comment
using PackageAnalyzer.CategorizeLines: Docstring
using PackageAnalyzer.CategorizeLines: LineCategories
using PackageAnalyzer.CategorizeLines: LineCategory
using PackageAnalyzer.CategorizeLines: categorize_lines!
``` …
```

Remove unnecessary explicit imports

---

README.md

closes #99 
I first added Zenodo oauth access for JuliaEcosystem, then turned it on for this repo, then used [this script](https://github.com/zenodo/zenodo/issues/1463#issuecomment-1007602828) to submit our latest existing release (rather than making a new tag).

Add zenodo DOI to readme

---

.github/workflows/ci.yml
Project.toml

Before this PR, CI runs on the following Julia versions:
- 1.6 (previous LTS)
- nightly
After this PR, CI runs on the following Julia versions:
- 1.6 (previous LTS)
- 1.10 (current LTS)
- nightly

CI: Add Julia 1.10 (the current LTS) to the CI matrix; also, drop support for 1.6

---

README.md

Support for Julia 1.6 through 1.9 was dropped in #109.

Update the README to reflect that PackageAnalyzer works on Julia 1.10 and later
